.translation: &translation-base
    image: crowdin/cli
    before_script:
    - "echo project_id: ${CROWDIN_PROJECT_ID} > ~/.crowdin.yml"
    - "echo api_token: ${CROWDIN_API_TOKEN} >> ~/.crowdin.yml"
    script:
    - echo crowdin upload sources
    - crowdin upload sources

stages:
    - translation

translation:
  <<: *translation-base
