.translation: &translation-base
    image: crowdin/cli
    script:
    - echo crowdin upload sources
    - crowdin upload sources

stages:
    - translation

translation:
    stage: translation
    <<: *translation-base
