"base_url" : "https://api.crowdin.com"
"commit_message": "[ci skip]"

"preserve_hierarchy": true

files: [
 {
  "source" : "/i18n/building-metrics.en.ts",
  "dest": "/app/building-metrics/building-metrics.en.ts",
  "translation" : "/i18n/building-metrics.%two_letters_code%.ts",
  "update_option": "update_as_unapproved",
  "labels" : [
      "building-metrics"
    ]
 }
]